[package]
name = "euler"
version = "0.1.0"
authors = ["Alex McCausland <alex.mccausland@gatalabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primal = "0.2.3"
